### ISSUE TITLE
question about dem_mask.py

### ISSUE THREAD

**Issue by 123yaj** [dshean/demcoreg#46]
hello! When I run the program, an error shows that"http://edcintl.cr.usgs.gov/downloads/sciweb1/shared/gtc/downloads/bare2010.zip" can't access

**Comment by dshean** [comment]
Looks like that file moved.  I see the tiles are now here: https://glad.umd.edu/dataset/global-2010-bare-ground-30-m, with data download link at the bottom.  I don’t see a zip file, just a directory containing all of the tif files.  

Need to modify https://github.com/dshean/demcoreg/blob/master/demcoreg/get_bareground.sh to download these instead of the zip.

Alternatively, we may want to move toward using the global forest cover products or global canopy height products from 2019.  I believe the bare ground product was just the inverse of the canopy cover product, but maybe more sophisticated.

I don't have time to do this right now, but it should be a relatively small task if others would like to give it a try!

**Comment by jmichellehu** [comment]
Hi @123yaj, I put up a fix for the tile download, see this PR https://github.com/dshean/demcoreg/pull/47. Hope this helps
